model:
  model_name: facebook/mbart-large-50
  IN_LEN: 50
  OUT_LEN: 80

train:
  SEED: 42
  TRAIN_BATCH_SIZE: 64
  VALID_BATCH_SIZE: 1
  TRAIN_EPOCHS: 3
  VALID_EPOCHS: 1
  LEARNING_RATE: 0.00001

test:
  TEST_TOP_K: 40
